module.exports = [
    "programação",
    "sistema",
    "computador",
    "celular",
    "teclado",
    "disquete",
    "cd",
    "astronomia",
    "unipar",
    "quiabo",
    "churrasco",
    "alho",
    "cebola",
    "alface",
    "geografia",
    "matemática",
    "história",
    "português",
    "pão de alho",
    "Google",
    "Instagram",
    "YouTube",
    "Amazon",
    "Microsoft",
    "Apple",
    "Facebook"

]