// Palavras sorteadas para jogadores comuns. O impostor recebe só a categoria.
module.exports = [
  { palavra: "programação", categoria: "Tecnologia" },
  { palavra: "sistema", categoria: "Tecnologia" },
  { palavra: "computador", categoria: "Tecnologia" },
  { palavra: "celular", categoria: "Tecnologia" },
  { palavra: "teclado", categoria: "Tecnologia" },
  { palavra: "disquete", categoria: "Tecnologia" },
  { palavra: "cd", categoria: "Tecnologia" },
  { palavra: "astronomia", categoria: "Ciência" },
  { palavra: "unipar", categoria: "Educação" },
  { palavra: "quiabo", categoria: "Culinária" },
  { palavra: "churrasco", categoria: "Culinária" },
  { palavra: "alho", categoria: "Culinária" },
  { palavra: "cebola", categoria: "Culinária" },
  { palavra: "alface", categoria: "Culinária" },
  { palavra: "geografia", categoria: "Disciplinas" },
  { palavra: "matemática", categoria: "Disciplinas" },
  { palavra: "história", categoria: "Disciplinas" },
  { palavra: "português", categoria: "Disciplinas" },
  { palavra: "pão de alho", categoria: "Culinária" },
  { palavra: "Google", categoria: "Internet" },
  { palavra: "Instagram", categoria: "Internet" },
  { palavra: "YouTube", categoria: "Internet" },
  { palavra: "Amazon", categoria: "Internet" },
  { palavra: "Microsoft", categoria: "Internet" },
  { palavra: "Apple", categoria: "Internet" },
  { palavra: "Facebook", categoria: "Internet" },
  { palavra: "laboratório", categoria: "Educação" },
  { palavra: "microscópio", categoria: "Ciência" },
  { palavra: "algoritmo", categoria: "Tecnologia" },
  { palavra: "biblioteca", categoria: "Educação" },
];
